#!/usr/bin/perl
my ($first_num, $second_num);

print "Enter the first number:\n";
$first_num = is_number();

print "Enter the second number:\n";
$second_num = is_number();

if ($first_num > $second_num) {
    my $temp = $first_num;
    $first_num = $second_num;
    $second_num = $temp;
}

my $primes_ar = get_primes($first_num, $second_num);
print_primes ($primes_ar);

sub is_number {
    chomp(my $input = <STDIN>);
    while ($input =~ /\D/) {
        print "This is not a real number! Please enter again:\n";
        chomp($input = <STDIN>);
    }
    return $input;
}

sub get_primes {
    my @list = ($first_num..$second_num);
    my @primes;

    for my $i (@list) {
        my $prime_condition = 1;
        for my $j (2..($i - 1)) {
            if ( $i % $j == 0 ) {
                $prime_condition = 0;
                last;
            }
        }
        if ($prime_condition) {
            push @primes, $i;
        }
    }
    return \@primes;
}

#sub is_prime {
#    my $i = shift;
#
#    for my $j (2..($i - 1)) {
#        if ($i % $j == 0) {
#            return 0;
#        }
#    }
#
#    return 1;
#}


sub print_primes {
    print "The prime numbers are:\n";

    my @primes_def = @$primes_ar;

    foreach $_ (@primes_def) {
        print "$_\n";
    }
}
